### ISSUE TITLE
visual tree

### ISSUE THREAD

**Issue by muveso** [jushii/AsyncFSM#1]
Is there a way to visualize the behavior tree or create a new tree with nodes etc?

**Comment by jushii** [comment]
Unfortunately no. Something like that would be nice to have though!

**Comment by jushii** [comment]
> Is there a way to visualize the behavior tree or create a new tree with nodes etc?

Unfortunately no. Something like that would be very useful to have though!

**Comment by muveso** [comment]
> > Is there a way to visualize the behavior tree or create a new tree with nodes etc?
> 
> 
> 
> Unfortunately no. Something like that would be very useful to have though!

if you have time to do that, we can develop it as a template together.

I use both UniTask and DI (zenject or vcontainer) in my projects as default and it will be such a good solution to work with visual graphs, behavior trees etc. I don't have enough time to develop such a system alone.
